### ISSUE TITLE
연관게시물 관련 리팩토링 진행

### ISSUE THREAD

**Issue by ckaanf** [KOSA-ToT/tiary#87]
# 연관게시물 리팩토링
## 캐시 관련 리팩토링
- [x] 게시글 작성 시 로직 제대로 전파되는지 다시 한번 확인
- [x] 게시글 작성과 게시글 조회 로직을 분리하여 캐시에서 데이터 가져오는 것의 속도 상승
- [ ] ~랜덤한 게시물을 저장할 때 넣어야하나 가져올 때 넣어야하나 고민~
         -> 캐시 로직 변경 후 충분히 속도가 나와서 괜찮을듯
         
## TODO 
캐시 관리를 `Redis`로 변경해보기
